### ISSUE TITLE
JFYI comment on issue #112

### ISSUE THREAD

**Issue by wqweto** [erpnet/ErpNet.FP#113] opened 2019-10-07 06:32 UTC
[Line 59 in `BgDatecsCIslFiscalPrinterDriver.cs`](https://github.com/erpnet/ErpNet.FP/blob/master/ErpNet.FP.Core/Drivers/BgDatecs/BgDatecsCIslFiscalPrinterDriver.cs#L59) is probably incorrect.
```
    CommentTextMaxLength = 40, // Set by Datecs protocol
```
The underneath calculation of 42 symbols (from 57 mm paper width) minus 2 symbols for trailing # in comment lines is not holding true in reality and 36 is a the real limit on Datecs cash-registers for unknown reasons.

I can confirm that my (recent) DP-25 model here has the same artificial 36 symbols limitation on comment lines and this is not a bug in the firmware of OP's particular model.

It would have been perfect if Datecs had these documented somewhere so the limit can be confirmed not only empirically.

(Please don't close OP github issues so fast, if you want collaborators input that is.)

**Comment by g-vvv** [comment] 2019-10-07 06:34
Ok, but in reality is a firmware limitation, not a bug in ErpNet.FP..

**Comment by g-vvv** [comment] 2019-10-07 06:38
When somebody expects to write a comment spreaded between # and # it will be imposible to fill it up to. the end, which is the expectation. If I put a 36 symbols, they will. report a Bug, because it is less than 40. So the problem is within Datecs firmware.

**Comment by g-vvv** [comment] 2019-10-07 06:41
They should fix this issue on their own, but you are right, I should put 36 symbols, because otherwise the information will be cutout. So I will fix this "bug", which is defacto workaround over Datecs limitations, and the line will be not filled to the end, but there will be no cutouts.

**Comment by g-vvv** [comment] 2019-10-07 06:55
Ok, so now I will close this "bug" issue.

**Closed by g-vvv** 2019-10-07 06:55 UTC
Labels: bug, invalid
